Add a comment, to specify what to check.
jssarrazolaa/ror-social-scaffold pull request #5
Opened 2020-10-13 19:36 UTC by SigmaSam

# This is the line we added to accomplish the friendship v2
Created a mutual friendship method.

It changes the status of the friendship and creates another row to create the mutual friendship once the request is accepted.

# We advanced more than we had to in the Friendship v1 Milestone and added the functionality that we were supposed to add in this milestone.

2020-10-13 20:09 UTC, kubilaycaglayan requested changes
Hello Team 👋
Status: Changes Required ♻️

Great job! As you are telling, it is working nicely. 🎉👍

Let's cover some details to make it better, together 😊

## [REQUIRED] Tests

- [x] **Add unit and integration tests.** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png)  from  [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

💡 Currently, we only have 3 tests.

## [OPTIONAL] Routes

- [x] In the routes file, there are non CRUD routes linking to the actions in the controllers that could be named as any CRUD operation, you can use this naming system and the default RESTful routes created by rails instead of linking different named actions. You can check the usage of member or collection routes or the creation of a new controller in the links. [Reference for explaining member routes](https://guides.rubyonrails.org/routing.html#adding-more-restful-actions). [Reference for suggesting a new controller](http://jeromedalbert.com/how-dhh-organizes-his-rails-controllers/)

## That's it, team! After making the changes you can request another review 👍😊

With all my respect 🙏
> Kubilay Caglayan | Technical Support Engineer

2020-10-14 00:12 UTC, voscarmv requested changes
# Impressive work, team! 🖥️ 👀 ✨ 

- Great work applying the requested changes and fulfilling most of the required features.

## However, some changes are still required... 🧰 🔨 🔧 

- The naming convention for your test suite are too ambiguous. Please read my code comments for details on how to fix this.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-10-14 00:12 UTC, voscarmv commented on spec/controllers/comments_spec.rb
> +  end
The `it` names for these tests are exactly the same, even though they test for opposite things. Please assign proper names for each of these tests, such as `"Comment creation fails with wrong parameters"` and `"Comment creation succeeds with valid parameters,"`.

2020-10-14 00:12 UTC, voscarmv commented on spec/controllers/likes_spec.rb
> +  end
Same as before. Please use proper names to distinguish the nature of the tests.

2020-10-14 00:12 UTC, voscarmv commented on spec/models/user_spec.rb
> +end
Same as before. Please use proper names to distinguish the nature of the tests.

2020-10-14 05:29 UTC, tirthajyoti-ghosh approved these changes
# Approved ✅

## You have done an incredible job making this project 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of the project. Go ahead and merge it! Onto the next project 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-10-14 11:06 UTC, merged